[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# fix planet discovery
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if (not v.config.softlock or G.GAME.hands[v.config.hand_type].played > 0) then"
position = "at"
payload = "if SMODS.is_poker_hand_visible(v.config.hand_type) then"
match_indent = true